# Generated by Django 4.0.4 on 2022-05-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_name', models.CharField(default='', max_length=25, null=True)),
                ('course_teaching', models.CharField(default='', max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(default='', max_length=25, null=True)),
                ('course_desc', models.CharField(default='', max_length=300, null=True)),
            ],
        ),
    ]
