# Generated by Django 4.0.4 on 2022-05-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycourse',
            name='course_name',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
